version: 2
updates:
  - package-ecosystem: "npm"   # Uses "npm" cause I'm using Node.js
    directory: "/"             # Location of package.json and package-lock.json
    schedule:
      interval: "weekly"        # Checks for updates once a week
    open-pull-requests-limit: 5 # Limits the number of open PRs
